from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH


def format_docx(text, doc_type):

    document = Document()

    # Title
    title = document.add_paragraph()

    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run(doc_type.upper())

    run.bold = True
    run.font.size = Pt(18)

    # Body
    for paragraph in text.split("\n"):

        if paragraph.strip():

            p = document.add_paragraph()

            p.paragraph_format.space_after = Pt(8)

            run = p.add_run(paragraph.strip())

            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

    # Footer
    section = document.sections[0]

    footer = section.footer

    footer_paragraph = footer.paragraphs[0]

    footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_paragraph.text = "Generated by LegalEase"

    return document
