from fpdf import FPDF


class LegalPDF(FPDF):

    def header(self):

        self.set_font("Arial", "B", 14)

        self.cell(
            0,
            10,
            "LegalEase",
            align="C"
        )

        self.ln(10)

    def footer(self):

        self.set_y(-15)

        self.set_font("Arial", "I", 8)

        self.cell(
            0,
            10,
            "Generated by LegalEase",
            align="C"
        )


def format_pdf(text, doc_type):

    pdf = LegalPDF()

    pdf.add_page()

    pdf.set_font("Arial", "B", 16)

    pdf.cell(
        0,
        10,
        doc_type,
        align="C"
    )

    pdf.ln(15)

    pdf.set_font("Arial", "", 11)

    for paragraph in text.split("\n"):

        if paragraph.strip():

            pdf.multi_cell(
                0,
                7,
                paragraph.strip()
            )

            pdf.ln(2)

    return pdf
